// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	PriceInCents int32              `json:"price_in_cents"`
	Quantity     int32              `json:"quantity"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
